export const ENDPOINTS = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    me: "/auth/me",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
  },
  users: {
    list: "/users",
    byId: (id: string) => `/users/${id}`,
    detail: (id: string) => `/users/${id}/detail`,
    changeStatus: (id: string) => `/users/${id}/status`,
    activity: (id: string) => `/users/${id}/activity`,
    create: "/users",
    update: (id: string) => `/users/${id}`,
    delete: (id: string) => `/users/${id}`,
    bulkStatus: "/users/bulk-status",
    bulkDelete: "/users/bulk-delete",
  },
  roles: {
    list: "/roles",
    byId: (id: string) => `/roles/${id}`,
    create: "/roles",
    update: (id: string) => `/roles/${id}`,
    delete: (id: string) => `/roles/${id}`,
  },
  dashboard: {
    stats: "/dashboard/stats",
    kpis: "/dashboard/kpis",
    recentActivity: "/dashboard/activity",
    analytics: "/dashboard/analytics",
    quickActions: "/dashboard/quick-actions",
    announcement: "/dashboard/announcement",
    announcements: "/announcements",
    announcementBanner: "/dashboard/announcement-banner",
  },
  colleges: {
    list: "/colleges",
    byId: (id: string) => `/colleges/${id}`,
    create: "/colleges",
    update: (id: string) => `/colleges/${id}`,
    delete: (id: string) => `/colleges/${id}`,
  },
  departments: {
    list: "/departments",
    byId: (id: string) => `/departments/${id}`,
    create: "/departments",
    update: (id: string) => `/departments/${id}`,
    delete: (id: string) => `/departments/${id}`,
  },
  programs: {
    list: "/programs",
    byId: (id: string) => `/programs/${id}`,
    create: "/programs",
    update: (id: string) => `/programs/${id}`,
    delete: (id: string) => `/programs/${id}`,
  },
  courses: {
    list: "/courses",
    byId: (id: string) => `/courses/${id}`,
    create: "/courses",
    update: (id: string) => `/courses/${id}`,
    delete: (id: string) => `/courses/${id}`,
  },
  academicYears: {
    list: "/academic-years",
    byId: (id: string) => `/academic-years/${id}`,
    create: "/academic-years",
    update: (id: string) => `/academic-years/${id}`,
    delete: (id: string) => `/academic-years/${id}`,
  },
  semesters: {
    listByYear: (yearId: string) => `/academic-years/${yearId}/semesters`,
    byId: (yearId: string, id: string) =>
      `/academic-years/${yearId}/semesters/${id}`,
    create: (yearId: string) => `/academic-years/${yearId}/semesters`,
    update: (yearId: string, id: string) =>
      `/academic-years/${yearId}/semesters/${id}`,
    delete: (yearId: string, id: string) =>
      `/academic-years/${yearId}/semesters/${id}`,
    activate: (yearId: string, id: string) =>
      `/academic-years/${yearId}/semesters/${id}/activate`,
    close: (yearId: string, id: string) =>
      `/academic-years/${yearId}/semesters/${id}/close`,
  },
  faculty: {
    list: "/faculty",
    byId: (id: string) => `/faculty/${id}`,
    create: "/faculty",
    update: (id: string) => `/faculty/${id}`,
    delete: (id: string) => `/faculty/${id}`,
  },
  staff: {
    list: "/staff",
    byId: (id: string) => `/staff/${id}`,
    create: "/staff",
    update: (id: string) => `/staff/${id}`,
    delete: (id: string) => `/staff/${id}`,
  },
  settings: {
    general: "/settings/general",
    mail: "/settings/mail",
    storage: "/settings/storage",
    security: "/settings/security",
    features: "/settings/features",
    backup: "/settings/backup",
    backupTrigger: "/settings/backup/trigger",
    backupHistory: "/settings/backup/history",
    maintenance: "/settings/maintenance",
    emailTemplates: "/settings/email-templates",
    emailTemplateById: (id: string) => `/settings/email-templates/${id}`,
    emailTemplatePreview: (id: string) =>
      `/settings/email-templates/${id}/preview`,
    emailTemplateReset: (id: string) =>
      `/settings/email-templates/${id}/reset`,
  },
  notifications: {
    list: "/notifications",
    byId: (id: string) => `/notifications/${id}`,
    recent: "/notifications/recent",
    markRead: (id: string) => `/notifications/${id}/read`,
    markUnread: (id: string) => `/notifications/${id}/unread`,
    markAllRead: "/notifications/read-all",
    delete: (id: string) => `/notifications/${id}`,
    preferences: "/notifications/preferences",
    preferencesReset: "/notifications/preferences/reset",
  },
  audit: {
    list: "/audit-logs",
    byId: (id: string) => `/audit-logs/${id}`,
    export: "/audit-logs/export",
  },
  reports: {
    list: "/reports",
    byId: (id: string) => `/reports/${id}`,
    generate: "/reports/generate",
    export: (id: string) => `/reports/${id}/export`,
  },
} as const;
