export const AUDIT_COPY = {
  pageTitle: "Audit & monitoring",
  pageDescription:
    "Review compliance audit logs, authentication history, and infrastructure system events.",
  tabLogs: "Audit logs",
  tabLoginHistory: "Login history",
  tabSystemEvents: "System events",
  exportSuccess: "Export started",
  exportSuccessDescription: "Your CSV file download should begin shortly.",
  exportError: "Export failed",
  loadErrorTitle: "Could not load records",
  loadErrorDescription: "Try again or contact support if the problem continues.",
  emptyLogsTitle: "No audit logs",
  emptyLogsDescription: "No records match the current filters.",
  emptyLoginTitle: "No login events",
  emptyLoginDescription: "No authentication events match the current filters.",
  emptyEventsTitle: "No system events",
  emptyEventsDescription: "No system events match the current filters.",
  viewDetail: "View details",
  backToLogs: "Back to audit logs",
  backToEvents: "Back to system events",
  logDetailTitle: "Audit log detail",
  eventDetailTitle: "System event detail",
  payloadChanges: "Changed fields",
  payloadBefore: "Before",
  payloadAfter: "After",
  contextPayload: "Event context",
  summarySection: "Summary",
  suspiciousLabel: "Suspicious activity",
  filterActor: "Actor",
  filterAction: "Action",
  filterResourceType: "Resource type",
  filterResult: "Result",
  filterDateRange: "Date range",
  filterUser: "User",
  filterLoginResult: "Result",
  filterCategory: "Category",
  filterSeverity: "Severity",
  exportFilenameLogs: "usns-audit-logs.csv",
  exportFilenameLogin: "usns-login-history.csv",
  exportFilenameEvents: "usns-system-events.csv",
} as const;

export const AUDIT_TAB_IDS = {
  logs: "logs",
  loginHistory: "login-history",
  systemEvents: "system-events",
} as const;

export const AUDIT_ALLOWED_ROLES = ["admin", "dba", "president"] as const;
