export const DATA_TABLE_COPY = {
  searchPlaceholder: "Search…",
  columnFilterPlaceholder: "Filter…",
  columnsLabel: "Columns",
  exportLabel: "Export",
  noDataTitle: "No records found",
  noDataDescription: "Try adjusting your search or filters.",
  selectAllLabel: "Select all rows",
  selectRowLabel: "Select row",
  actionsLabel: "Actions",
  selectedCount: (count: number) => `${count} selected`,
  pageLabel: "Page",
  ofLabel: "of",
  previousPage: "Previous page",
  nextPage: "Next page",
} as const;
