export const NOTIFICATIONS_COPY = {
  pageTitle: "Notification center",
  pageDescription:
    "Review system, academic, and security alerts. Manage read state and delivery preferences.",
  preferencesTab: "Preferences",
  centerTab: "Inbox",
  markAllRead: "Mark all as read",
  markRead: "Mark as read",
  markUnread: "Mark as unread",
  delete: "Delete",
  deleteTitle: "Delete notification?",
  deleteDescription:
    "This notification will be removed permanently. This action cannot be undone.",
  deleteConfirm: "Delete",
  cancel: "Cancel",
  markAllSuccess: "All notifications marked as read",
  markReadSuccess: "Notification marked as read",
  markUnreadSuccess: "Notification marked as unread",
  deleteSuccess: "Notification deleted",
  loadErrorTitle: "Could not load notifications",
  loadErrorDescription: "Try again or contact support if the problem continues.",
  emptyTitle: "No notifications",
  emptyDescription: "You are all caught up. New alerts will appear here.",
  emptyFilteredTitle: "No matching notifications",
  emptyFilteredDescription: "Adjust filters to see more results.",
  bellAriaLabel: "Notifications",
  bellAriaLabelUnread: "Notifications, {count} unread",
  bellEmpty: "No unread notifications",
  bellViewAll: "View all notifications",
  bellMarkRead: "Mark as read",
  preferencesTitle: "Notification preferences",
  preferencesDescription:
    "Choose which alerts you receive in the app and by email.",
  preferencesInApp: "In-app",
  preferencesEmail: "Email",
  preferencesReset: "Reset to defaults",
  preferencesResetTitle: "Reset preferences?",
  preferencesResetDescription:
    "All notification preferences will return to their default values.",
  preferencesResetConfirm: "Reset",
  preferencesSaved: "Preference saved",
  preferencesResetSuccess: "Preferences reset to defaults",
  preferencesLoadErrorTitle: "Could not load preferences",
  preferencesLoadErrorDescription: "Try again or contact support.",
  categorySystem: "System",
  categoryAcademic: "Academic",
  categorySecurity: "Security",
  filterCategory: "Category",
  filterReadStatus: "Read status",
  filterReadAll: "All",
  filterReadUnread: "Unread",
  filterReadRead: "Read",
  retry: "Retry",
} as const;

export const NOTIFICATIONS_TAB_IDS = {
  center: "center",
  preferences: "preferences",
} as const;
