export const ROLES_MANAGEMENT_COPY = {
  pageTitle: "Roles",
  pageDescription:
    "Manage dashboard roles, permission assignments, and access comparisons.",
  tabListLabel: "All roles",
  tabMatrixLabel: "Permission matrix",
  createRoleLabel: "Create role",
  createDrawerTitle: "Create role",
  createDrawerDescription:
    "Define a custom role with a name, description, and permission set.",
  editDrawerTitle: "Edit role",
  editDrawerDescription: "Update role details and assigned permissions.",
  viewDrawerTitle: "View role",
  viewDrawerDescription: "Read-only view of role configuration.",
  systemRoleBadge: "System",
  saveLabel: "Save changes",
  createLabel: "Create role",
  cancelLabel: "Cancel",
  closeLabel: "Close",
  emptyTitle: "No roles found",
  emptyDescription: "Try adjusting your search or create a custom role.",
  loadErrorTitle: "Unable to load roles",
  loadErrorDescription: "We could not load the role list. Please try again.",
  roleLoadErrorTitle: "Unable to load role",
  roleLoadErrorDescription: "We could not load this role record.",
  actionView: "View",
  actionEdit: "Edit",
  actionDelete: "Delete",
  deleteTitle: "Delete role?",
  deleteDescription: (name: string) =>
    `${name} will be removed. Users are not reassigned automatically.`,
  deleteConfirmLabel: "Delete",
  fieldName: "Role name",
  fieldDescription: "Description",
  permissionsLegend: "Permissions",
  selectAllGroup: (category: string) => `Select all in ${category}`,
  toastCreated: "Role created",
  toastUpdated: "Role updated",
  toastDeleted: "Role deleted",
  formErrorGeneric: "Could not save role. Check the form and try again.",
  matrixTitle: "Permission matrix",
  matrixDescription:
    "Compare granted permissions across all roles. Filter by category or export to CSV.",
  matrixFilterLabel: "Permission group",
  matrixFilterPlaceholder: "All groups",
  matrixExportLabel: "Export CSV",
  matrixPermissionColumn: "Permission",
  matrixCategoryColumn: "Category",
  matrixGrantedLabel: "Granted",
  matrixDeniedLabel: "Denied",
  matrixExportSuccess: "Permission matrix exported",
  matrixLoadErrorTitle: "Unable to load matrix",
  matrixLoadErrorDescription: "We could not load the permission matrix.",
} as const;
