import type { UiKitUserRow } from "@/types/ui-kit.types";

export const UI_KIT_DEMO_USERS: UiKitUserRow[] = [
  {
    id: "usr_001",
    name: "Ahmed Al-Rashidi",
    email: "ahmed@usns.edu",
    role: "President",
    department: "Executive",
    status: "Active",
  },
  {
    id: "usr_002",
    name: "Sara Mitchell",
    email: "sara@usns.edu",
    role: "Dean",
    department: "Engineering",
    status: "Active",
  },
  {
    id: "usr_003",
    name: "James Okonkwo",
    email: "james@usns.edu",
    role: "DBA",
    department: "IT",
    status: "Active",
  },
  {
    id: "usr_004",
    name: "Elena Vasquez",
    email: "elena@usns.edu",
    role: "Admin",
    department: "Operations",
    status: "Active",
  },
  {
    id: "usr_005",
    name: "Marcus Chen",
    email: "marcus@usns.edu",
    role: "Faculty",
    department: "Computer Science",
    status: "Active",
  },
  {
    id: "usr_006",
    name: "Fatima Hassan",
    email: "fatima@usns.edu",
    role: "Faculty",
    department: "Mathematics",
    status: "Pending",
  },
  {
    id: "usr_007",
    name: "Omar Farouk",
    email: "omar@usns.edu",
    role: "Staff",
    department: "Registrar",
    status: "Active",
  },
  {
    id: "usr_008",
    name: "Priya Sharma",
    email: "priya@usns.edu",
    role: "Faculty",
    department: "Biology",
    status: "Active",
  },
  {
    id: "usr_009",
    name: "David Kim",
    email: "david@usns.edu",
    role: "Staff",
    department: "Finance",
    status: "Inactive",
  },
  {
    id: "usr_010",
    name: "Aisha Mohammed",
    email: "aisha@usns.edu",
    role: "Dean",
    department: "Arts",
    status: "Active",
  },
  {
    id: "usr_011",
    name: "Lucas Berg",
    email: "lucas@usns.edu",
    role: "Faculty",
    department: "Physics",
    status: "Active",
  },
  {
    id: "usr_012",
    name: "Nina Petrov",
    email: "nina@usns.edu",
    role: "Admin",
    department: "Admissions",
    status: "Pending",
  },
  {
    id: "usr_013",
    name: "Carlos Mendez",
    email: "carlos@usns.edu",
    role: "Staff",
    department: "HR",
    status: "Active",
  },
  {
    id: "usr_014",
    name: "Yuki Tanaka",
    email: "yuki@usns.edu",
    role: "Faculty",
    department: "Chemistry",
    status: "Active",
  },
  {
    id: "usr_015",
    name: "Rachel Brooks",
    email: "rachel@usns.edu",
    role: "Faculty",
    department: "English",
    status: "Inactive",
  },
  {
    id: "usr_016",
    name: "Hassan Ali",
    email: "hassan@usns.edu",
    role: "Staff",
    department: "Library",
    status: "Active",
  },
  {
    id: "usr_017",
    name: "Sophie Laurent",
    email: "sophie@usns.edu",
    role: "Dean",
    department: "Medicine",
    status: "Active",
  },
  {
    id: "usr_018",
    name: "Michael O'Brien",
    email: "michael@usns.edu",
    role: "Faculty",
    department: "History",
    status: "Active",
  },
  {
    id: "usr_019",
    name: "Amara Diallo",
    email: "amara@usns.edu",
    role: "Admin",
    department: "Communications",
    status: "Pending",
  },
  {
    id: "usr_020",
    name: "Tomás Rivera",
    email: "tomas@usns.edu",
    role: "Faculty",
    department: "Economics",
    status: "Active",
  },
  {
    id: "usr_021",
    name: "Grace Wilson",
    email: "grace@usns.edu",
    role: "Staff",
    department: "Facilities",
    status: "Active",
  },
  {
    id: "usr_022",
    name: "Ibrahim Saleh",
    email: "ibrahim@usns.edu",
    role: "DBA",
    department: "IT",
    status: "Active",
  },
];
