export const USERS_COPY = {
  pageTitle: "Users",
  pageDescription:
    "Manage accounts, roles, and access for administration dashboard users.",
  createUserLabel: "Create user",
  createDrawerTitle: "Create user",
  createDrawerDescription:
    "Add a new dashboard user with role and department assignment.",
  editDrawerTitle: "Edit user",
  editDrawerDescription: "Update account details and access settings.",
  viewDrawerTitle: "User profile",
  viewDrawerDescription: "Read-only view of user account details.",
  saveLabel: "Save changes",
  createLabel: "Create user",
  cancelLabel: "Cancel",
  closeLabel: "Close",
  emptyTitle: "No users found",
  emptyDescription: "Try adjusting your search or filters, or create a user.",
  loadErrorTitle: "Unable to load users",
  loadErrorDescription: "We could not load the user list. Please try again.",
  userLoadErrorTitle: "Unable to load user",
  userLoadErrorDescription: "We could not load this user record.",
  actionViewProfile: "View profile",
  actionEditUser: "Edit user",
  actionActivate: "Activate",
  actionDeactivate: "Deactivate",
  actionDelete: "Delete",
  bulkActivate: "Activate selected",
  bulkDeactivate: "Deactivate selected",
  bulkDelete: "Delete selected",
  deleteTitle: "Delete user?",
  deleteDescription: (name: string) =>
    `${name} will lose access immediately. This cannot be undone.`,
  bulkDeleteTitle: "Delete selected users?",
  bulkDeleteDescription: (count: number) =>
    `${count} users will be deleted. This cannot be undone.`,
  deleteConfirmLabel: "Delete",
  roleChangeTitle: "Change your role?",
  roleChangeDescription:
    "Lowering your own role may remove administrative permissions. Continue only if you are sure.",
  roleChangeConfirmLabel: "Confirm change",
  toastCreated: "User created",
  toastUpdated: "User updated",
  toastDeleted: "User deleted",
  toastActivated: "User activated",
  toastDeactivated: "User deactivated",
  toastBulkActivated: (count: number) => `${count} users activated`,
  toastBulkDeactivated: (count: number) => `${count} users deactivated`,
  toastBulkDeleted: (count: number) => `${count} users deleted`,
  formErrorGeneric: "Could not save user. Check the form and try again.",
  fieldFullName: "Full name",
  fieldEmail: "Email",
  fieldRole: "Role",
  fieldDepartment: "Department",
  fieldTemporaryPassword: "Temporary password",
  fieldForcePasswordChange: "Require password change on first sign-in",
  selectRolePlaceholder: "Select a role",
  selectDepartmentPlaceholder: "Select a department",
} as const;
