export const PROFILE_TAB_IDS = {
  profile: "profile",
  password: "password",
  preferences: "preferences",
} as const;

export type ProfileTabId =
  (typeof PROFILE_TAB_IDS)[keyof typeof PROFILE_TAB_IDS];

export const PROFILE_COPY = {
  pageTitle: "Profile & account",
  pageDescription:
    "Manage your personal information, password, and display preferences.",
  tabProfile: "Profile",
  tabPassword: "Password",
  tabPreferences: "Preferences",
  sectionProfile: "My profile",
  sectionPassword: "Change password",
  sectionPreferences: "Account preferences",
  fieldFullName: "Full name",
  fieldDisplayName: "Display name",
  fieldEmail: "Email",
  fieldRole: "Role",
  fieldDepartment: "Department",
  fieldJoinDate: "Join date",
  fieldPhone: "Phone",
  fieldBio: "Bio",
  fieldCurrentPassword: "Current password",
  fieldNewPassword: "New password",
  fieldConfirmPassword: "Confirm new password",
  fieldLanguage: "Language",
  fieldTimezone: "Timezone",
  fieldDateFormat: "Date format",
  fieldTheme: "Theme",
  editProfile: "Edit profile",
  cancelEdit: "Cancel",
  saveProfile: "Save changes",
  changeAvatar: "Change photo",
  uploadAvatarTitle: "Update profile photo",
  uploadAvatarDescription:
    "Choose an image and adjust the crop. Preview only — no file is uploaded to a server.",
  uploadAvatarChoose: "Choose image",
  uploadAvatarApply: "Apply photo",
  uploadAvatarCancel: "Cancel",
  uploadAvatarScale: "Zoom",
  updatePassword: "Update password",
  savePreferences: "Save preferences",
  loadErrorTitle: "Could not load profile",
  loadErrorDescription: "Try again or sign in again if the problem continues.",
  preferencesLoadErrorTitle: "Could not load preferences",
  preferencesLoadErrorDescription: "Try again in a moment.",
  saveSuccessTitle: "Profile updated",
  saveSuccessDescription: "Your profile changes have been saved.",
  avatarSuccessTitle: "Photo updated",
  avatarSuccessDescription: "Your profile photo has been updated.",
  passwordSuccessTitle: "Password updated",
  passwordSuccessDescription: "Your password has been changed successfully.",
  preferencesSuccessTitle: "Preferences saved",
  preferencesSuccessDescription: "Your account preferences are now active.",
  saveErrorTitle: "Save failed",
  passwordErrorTitle: "Could not update password",
  wrongCurrentPassword: "Current password is incorrect.",
  preferencesDescription:
    "Language selection is for display preferences only. Theme and date format apply immediately.",
} as const;
